/* ----------------------------------------------------------------------
 * THREE-PASS WALK SCHEDULER -- logic module
 * ----------------------------------------------------------------------
 * Direct JS port of walk_scheduler.py, the reusable module derived from the
 * manual walkthrough of the 8/17/2026 schedule (see the walk-assignment-
 * first-pass-logic.md writeup for the narrative version of these rules).
 * This is the sole source of truth for the three-pass algorithm; the
 * browser build (dev/three-pass-scheduler-client.js, generated by
 * dev/build-three-pass-client.js) must never diverge from it.
 *
 * This module replaces the old route-constrained optimizer
 * (route_constrained_optimizer_logic.js and everything downstream of it),
 * which is being removed in full because this three-pass approach is the
 * validated, currently-used methodology.
 *
 * Pass 1 -- build the day from an empty roster, scarcity-first
 *           (orphan/lopsided communities resolved before easy ones),
 *           home-affinity -> route-affinity -> nearest-distance tiers,
 *           hard 45/60-min leg caps.
 * Pass 2 -- resolve whatever Pass 1 couldn't place, using LIVE manager
 *           state (not a fresh day), including one-hop cascading trades
 *           when the best direct option still has a bad leg.
 * Pass 3 -- sanity check the final result: duplicate jobs, cap violations,
 *           3+-community spans (informational), double-booked time slots.
 *
 * Nothing in this file talks to Airtable or the network. It operates on
 * plain data handed to it by the caller.
 *
 * Usage:
 *   const scheduler = new ThreePassScheduler({
 *     walks,               // array of { job, community, base, address, type, time }
 *     managerHomes,        // { managerName: homeBaseCommunity }
 *     driveMatrix,         // Map or plain object keyed "from|to" -> minutes
 *     managerCaps,         // optional { managerName: hours }, default 8.0
 *     managerExcludedTypes // optional { managerName: Set(["CEL","ACC"]) or array }
 *   });
 *   scheduler.runAll();
 *   scheduler.printReport();
 *
 * WALK SCHEMA (each item in `walks`):
 *   { job: "12345", community: "Ranches 50GC", base: "Ranches",
 *     address: "123 Main St", type: "QAI"|"QAA"|"CEL"|"ACC",
 *     time: "9 am"|"12 pm"|"3 pm"|null }
 * ---------------------------------------------------------------------- */

const HOURS_BY_TYPE = { QAI: 2.0, QAA: 1.0, CEL: 2.0, ACC: 1.0 };
const DEFAULT_CAP = 8.0;
const INITIAL_LEG_CAP = 45;   // minutes -- cap for a manager's first stop of the day
const REBALANCE_LEG_CAP = 60; // minutes -- cap for filling out an already-anchored day
const TIME_ORDER = { '9 am': 0, '12 pm': 1, '3 pm': 2, null: 3 };

/* driveMatrix keys are normalized "from|to" strings so either a plain object
 * or a Map works as input -- the Python version used a dict keyed by
 * (from, to) tuples, which JS has no native equivalent for. */
function driveKey(a, b) { return a + '|' + b; }

class ThreePassScheduler {
  constructor({ walks, managerHomes, driveMatrix, managerCaps, managerExcludedTypes }) {
    this.walks = walks;
    this.managerHomes = managerHomes;
    this.driveMatrix = driveMatrix instanceof Map ? driveMatrix : new Map(Object.entries(driveMatrix || {}));
    this.managerCaps = managerCaps || {};
    this.managerExcludedTypes = {};
    for (const [m, types] of Object.entries(managerExcludedTypes || {})) {
      this.managerExcludedTypes[m] = new Set(types);
    }
    this.managers = Object.keys(managerHomes);

    // live state, built up across Pass 1 and Pass 2
    this.hours = Object.fromEntries(this.managers.map(m => [m, 0.0]));
    this.slotsUsed = Object.fromEntries(this.managers.map(m => [m, new Set()]));
    this.stops = Object.fromEntries(this.managers.map(m => [m, []])); // base communities visited
    this.assignments = []; // { manager, job, base, type, time, hours, leg, note }
    this.supportRoleAssignments = []; // walks given to non-QAM support roles
    this.held = []; // walks that never found a home
    this.pass3Results = null;
  }

  // ---------- shared helpers ----------

  capFor(manager) {
    return Object.prototype.hasOwnProperty.call(this.managerCaps, manager)
      ? this.managerCaps[manager] : DEFAULT_CAP;
  }

  drive(a, b) {
    if (a === b) return 0;
    if (this.driveMatrix.has(driveKey(a, b))) return this.driveMatrix.get(driveKey(a, b));
    if (this.driveMatrix.has(driveKey(b, a))) return this.driveMatrix.get(driveKey(b, a));
    return null;
  }

  /* Shortest drive from any of a manager's current stops (or home if none yet). */
  bestLeg(manager, base) {
    if (this.stops[manager].length) {
      let min = Infinity;
      for (const s of this.stops[manager]) {
        const d = this.drive(s, base);
        const v = d === null ? 9999 : d;
        if (v < min) min = v;
      }
      return min;
    }
    const d = this.drive(this.managerHomes[manager], base);
    return d === null ? 9999 : d;
  }

  room(manager) {
    return this.capFor(manager) - this.hours[manager];
  }

  isExcluded(manager, wtype) {
    const set = this.managerExcludedTypes[manager];
    return !!set && set.has(wtype);
  }

  commit(manager, walk, leg, note = '') {
    const h = HOURS_BY_TYPE[walk.type];
    this.hours[manager] += h;
    if (walk.time) this.slotsUsed[manager].add(walk.time);
    this.stops[manager].push(walk.base);
    this.assignments.push({
      manager, job: walk.job, base: walk.base, type: walk.type,
      time: walk.time, hours: h, leg, note,
    });
  }

  /* Remove a previously committed walk from a manager (used for cascades). */
  uncommit(manager, job) {
    for (let i = 0; i < this.assignments.length; i++) {
      const row = this.assignments[i];
      if (row.manager === manager && row.job === job) {
        this.assignments.splice(i, 1);
        this.hours[manager] -= row.hours;
        if (row.time) this.slotsUsed[manager].delete(row.time);
        const idx = this.stops[manager].indexOf(row.base);
        if (idx !== -1) this.stops[manager].splice(idx, 1);
        return { job: row.job, base: row.base, type: row.type, time: row.time };
      }
    }
    return null;
  }

  // ================= PASS 1 =================

  /* Build the day from scratch: scarcity-first community order, home
   * affinity first, then route affinity / nearest-distance tiers. */
  runPass1() {
    const baseCounts = {};
    const anchors = {};
    for (const w of this.walks) baseCounts[w.base] = (baseCounts[w.base] || 0) + 1;
    for (const [m, home] of Object.entries(this.managerHomes)) {
      (anchors[home] = anchors[home] || []).push(m);
    }

    const scarcity = (base) => {
      const n = (anchors[base] || []).length;
      return n === 0 ? baseCounts[base] : baseCounts[base] / n;
    };

    const scarcityOrder = Object.keys(baseCounts).sort((a, b) => scarcity(b) - scarcity(a));
    const baseRank = Object.fromEntries(scarcityOrder.map((b, i) => [b, i]));

    const queue = this.walks.slice().sort((a, b) => {
      const r = baseRank[a.base] - baseRank[b.base];
      if (r !== 0) return r;
      return TIME_ORDER[a.time] - TIME_ORDER[b.time];
    });

    const deferred = [];
    for (const w of queue) {
      const candidates = [];
      const h = HOURS_BY_TYPE[w.type];
      for (const m of this.managers) {
        if (this.hours[m] + h > this.capFor(m) + 1e-9) continue;
        if (w.time && this.slotsUsed[m].has(w.time)) continue;
        if (this.isExcluded(m, w.type)) continue;
        const leg = this.bestLeg(m, w.base);
        candidates.push([leg, this.hours[m], m]);
      }
      if (!candidates.length) { deferred.push(w); continue; }
      candidates.sort((a, b) => (a[0] - b[0]) || (a[1] - b[1]));
      const [leg, , m] = candidates[0];
      if (leg > INITIAL_LEG_CAP && !this.stops[m].length) {
        // no one within the initial cap; still the best available,
        // but only accept it here if it's genuinely the sole option --
        // otherwise defer to Pass 2 which searches harder.
        deferred.push(w);
        continue;
      }
      this.commit(m, w, leg);
    }

    this.held = deferred;
    return this;
  }

  // ================= PASS 2 =================

  /* Resolve whatever Pass 1 deferred, using live state and one-hop
   * cascading trades when the direct best option still has a bad leg. */
  runPass2(maxCascadeHops = 1) {
    const stillOpen = [];
    for (const w of this.held.slice()) {
      let result = this._bestCandidate(w, REBALANCE_LEG_CAP);
      if (result) { this.commit(result.m, w, result.leg); continue; }

      // try a one-hop cascade: find the manager truly closest by existing
      // stop, see what's blocking them, and try to relocate it
      const cascaded = maxCascadeHops >= 1 ? this._tryCascade(w) : false;
      if (!cascaded) {
        // last resort: force onto the least-bad option with any room
        result = this._bestCandidate(w, null);
        if (result) {
          this.commit(result.m, w, result.leg, `FORCED - ${result.leg}min, no better option`);
        } else {
          stillOpen.push(w);
        }
      }
    }
    this.held = stillOpen;
    return this;
  }

  _bestCandidate(walk, legCap, exclude) {
    exclude = exclude || new Set();
    const h = HOURS_BY_TYPE[walk.type];
    const candidates = [];
    for (const m of this.managers) {
      if (exclude.has(m)) continue;
      if (this.hours[m] + h > this.capFor(m) + 1e-9) continue;
      if (walk.time && this.slotsUsed[m].has(walk.time)) continue;
      if (this.isExcluded(m, walk.type)) continue;
      const leg = this.bestLeg(m, walk.base);
      if (legCap !== null && legCap !== undefined && leg > legCap) continue;
      candidates.push([leg, this.hours[m], m]);
    }
    if (!candidates.length) return null;
    candidates.sort((a, b) => (a[0] - b[0]) || (a[1] - b[1]));
    const [leg, , m] = candidates[0];
    return { leg, m };
  }

  /* Find the manager genuinely closest to `walk` by existing stop, even if
   * blocked; try to move their blocking walk to a third manager to free
   * them up. Returns true if the cascade succeeded. */
  _tryCascade(walk) {
    const hNeeded = HOURS_BY_TYPE[walk.type];

    // rank ALL managers by proximity via existing stops (ignore blocks for now)
    const ranked = this.managers.slice().sort((a, b) => this.bestLeg(a, walk.base) - this.bestLeg(b, walk.base));

    for (const m of ranked.slice(0, 5)) { // only worth checking the closest few
      if (this.isExcluded(m, walk.type)) continue;
      const slotBlocked = !!walk.time && this.slotsUsed[m].has(walk.time);
      const roomShort = this.room(m) < hNeeded;

      if (!slotBlocked && !roomShort) continue; // would have already been picked up directly

      // find a blocking walk of theirs to relocate: prefer one that occupies
      // the needed slot, else any walk with enough hours to free up the room
      let blocking = null;
      for (const row of this.assignments) {
        if (row.manager !== m) continue;
        if (slotBlocked && row.time === walk.time) { blocking = row.job; break; }
        if (roomShort && row.hours >= hNeeded - this.room(m)) { blocking = row.job; break; }
      }
      if (!blocking) continue;

      const displaced = this.uncommit(m, blocking);
      if (displaced === null) continue;

      const displacedWalk = { job: displaced.job, base: displaced.base, type: displaced.type, time: displaced.time };

      // can this manager now take the target walk?
      const stillBlocked = !!walk.time && this.slotsUsed[m].has(walk.time);
      if (!stillBlocked && this.room(m) >= hNeeded) {
        const newHome = this._bestCandidate(displacedWalk, REBALANCE_LEG_CAP, new Set([m]));
        if (newHome) {
          this.commit(newHome.m, displacedWalk, newHome.leg, 'cascade - displaced');
          const targetLeg = this.bestLeg(m, walk.base);
          this.commit(m, walk, targetLeg, 'cascade - freed by displacing walk above');
          return true;
        }
        // couldn't rehome the displaced walk; put it back, this attempt failed
        this.commit(m, displacedWalk, 0, '(re-committed, cascade aborted)');
        continue;
      } else {
        // uncommitting didn't actually free the manager for the target walk
        // (wrong blocker, or still short on hours) -- restore the displaced
        // walk and move on to the next candidate manager
        this.commit(m, displacedWalk, 0, '(re-committed, cascade aborted)');
        continue;
      }
    }
    return false;
  }

  // ================= PASS 3 =================

  runPass3(communityFlagThreshold = 3) {
    const jobs = this.assignments.map(row => row.job);
    const jobCounts = {};
    for (const j of jobs) jobCounts[j] = (jobCounts[j] || 0) + 1;
    const duplicates = Object.fromEntries(Object.entries(jobCounts).filter(([, c]) => c > 1));

    const overCap = {};
    for (const [m, total] of Object.entries(this.hours)) {
      const cap = this.capFor(m);
      if (total > cap + 1e-9) {
        overCap[m] = { hours: total, cap, overBy: Math.round((total - cap) * 100) / 100 };
      }
    }

    const communitiesByManager = {};
    for (const row of this.assignments) {
      (communitiesByManager[row.manager] = communitiesByManager[row.manager] || new Set()).add(row.base);
    }
    const multiCommunity = {};
    for (const [m, set] of Object.entries(communitiesByManager)) {
      if (set.size >= communityFlagThreshold) multiCommunity[m] = Array.from(set).sort();
    }

    const slotsByManager = {};
    for (const row of this.assignments) {
      if (!row.time) continue;
      slotsByManager[row.manager] = slotsByManager[row.manager] || {};
      (slotsByManager[row.manager][row.time] = slotsByManager[row.manager][row.time] || [])
        .push([row.job, row.base, row.type]);
    }
    const doubleBooked = {};
    for (const [m, byTime] of Object.entries(slotsByManager)) {
      const conflicts = Object.fromEntries(Object.entries(byTime).filter(([, w]) => w.length > 1));
      if (Object.keys(conflicts).length) doubleBooked[m] = conflicts;
    }

    this.pass3Results = {
      duplicates,
      overCap,
      multiCommunity,
      doubleBooked,
      totalWalks: jobs.length,
      uniqueWalks: new Set(jobs).size,
      held: this.held.length,
    };
    return this.pass3Results;
  }

  // ================= orchestration + reporting =================

  runAll() {
    this.runPass1();
    this.runPass2();
    this.runPass3();
    return this;
  }

  printReport() {
    const lines = [];
    lines.push('='.repeat(60));
    lines.push(`SCHEDULE RESULT -- ${this.assignments.length} placed, ${this.held.length} held`);
    lines.push('='.repeat(60));
    for (const m of Object.keys(this.hours).sort((a, b) => this.hours[b] - this.hours[a])) {
      lines.push(`  ${m.padEnd(20)} ${this.hours[m].toFixed(1)}h  (cap ${this.capFor(m)}h)`);
    }
    if (this.held.length) {
      lines.push('');
      lines.push('HELD (no feasible placement found):');
      for (const w of this.held) lines.push(`  ${w.job} ${w.base} ${w.type} ${w.time}`);
    }

    const r = this.pass3Results;
    lines.push('');
    lines.push('='.repeat(60));
    lines.push('PASS 3 -- SANITY CHECK');
    lines.push('='.repeat(60));
    lines.push(`Total: ${r.totalWalks} rows, ${r.uniqueWalks} unique jobs`);
    lines.push('Duplicates: ' + (Object.keys(r.duplicates).length ? JSON.stringify(r.duplicates) : 'NONE'));
    lines.push('Over cap: ' + (Object.keys(r.overCap).length ? JSON.stringify(r.overCap) : 'NONE'));
    lines.push('3+ communities (informational): ' + (Object.keys(r.multiCommunity).length ? JSON.stringify(r.multiCommunity) : 'NONE'));
    lines.push('Double-booked slots: ' + (Object.keys(r.doubleBooked).length ? JSON.stringify(r.doubleBooked) : 'NONE'));

    const out = lines.join('\n');
    // eslint-disable-next-line no-console
    console.log(out);
    return out;
  }
}

module.exports = {
  HOURS_BY_TYPE,
  DEFAULT_CAP,
  INITIAL_LEG_CAP,
  REBALANCE_LEG_CAP,
  TIME_ORDER,
  ThreePassScheduler,
};
